version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestGitPullProject
  gitServerName: SanthoshKAccount1D
  gitUrl: https://github.com/santhu736852/TestGitPullProject
  gitUsername: santhu736852
  gitBranch: main
